sentry.Begin(sentry_mode_e.kI2CMode, sentry2_addr_e.ADDR1)
sentry.CameraSetAwb(sentry_camera_white_balance_e.kAutoWhiteBalance)
sentry.VisionSetStatus(sentry2_status.Enable, sentry_vision_e.kVisionColor)
sentry.SetParamNum(sentry_vision_e_2.kVisionColor, 1)
sentry.SetColorParam(50, 50, 3, 4, 1)
sentry.SetBlobParam(3, 4, color_label_e.kColorRed, 1)
sentry.SetCustomParam(0, 0, 0, 0, 0, 1)
